//-----------------------------------------------------------------------------
// <auto-generated> 
//   This code was generated by a tool. 
// 
//   Changes to this file may cause incorrect behavior and will be lost if  
//   the code is regenerated.
//
//   Tool: AllJoynCodeGenerator.exe
//
//   This tool is located in the Windows 10 SDK and the Windows 10 AllJoyn 
//   Visual Studio Extension in the Visual Studio Gallery.  
//
//   The generated code should be packaged in a Windows 10 C++/CX Runtime  
//   Component which can be consumed in any UWP-supported language using 
//   APIs that are available in Windows.Devices.AllJoyn.
//
//   Using AllJoynCodeGenerator - Invoke the following command with a valid 
//   Introspection XML file and a writable output directory:
//     AllJoynCodeGenerator -i <INPUT XML FILE> -o <OUTPUT DIRECTORY>
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

namespace org { namespace alljoyn { namespace SmartSpaces { namespace Environment { namespace CurrentHumidity {

// This class, and the associated EventArgs classes, exist for the benefit of JavaScript developers who
// do not have the ability to implement ICurrentHumidityService. Instead, CurrentHumidityServiceEventAdapter
// provides the Interface implementation and exposes a set of compatible events to the developer.
public ref class CurrentHumidityServiceEventAdapter sealed : [Windows::Foundation::Metadata::Default] ICurrentHumidityService
{
public:
    // Method Invocation Events
    // Property Read Events
    event Windows::Foundation::TypedEventHandler<CurrentHumidityServiceEventAdapter^, CurrentHumidityGetVersionRequestedEventArgs^>^ GetVersionRequested 
    { 
        Windows::Foundation::EventRegistrationToken add(Windows::Foundation::TypedEventHandler<CurrentHumidityServiceEventAdapter^, CurrentHumidityGetVersionRequestedEventArgs^>^ handler) 
        { 
            return _GetVersionRequested += ref new Windows::Foundation::EventHandler<Platform::Object^>
            ([handler](Platform::Object^ sender, Platform::Object^ args)
            {
                handler->Invoke(safe_cast<CurrentHumidityServiceEventAdapter^>(sender), safe_cast<CurrentHumidityGetVersionRequestedEventArgs^>(args));
            }, Platform::CallbackContext::Same);
        } 
        void remove(Windows::Foundation::EventRegistrationToken token) 
        { 
            _GetVersionRequested -= token; 
        } 
    internal: 
        void raise(CurrentHumidityServiceEventAdapter^ sender, CurrentHumidityGetVersionRequestedEventArgs^ args) 
        { 
            _GetVersionRequested(sender, args);
        } 
    }

    event Windows::Foundation::TypedEventHandler<CurrentHumidityServiceEventAdapter^, CurrentHumidityGetCurrentValueRequestedEventArgs^>^ GetCurrentValueRequested 
    { 
        Windows::Foundation::EventRegistrationToken add(Windows::Foundation::TypedEventHandler<CurrentHumidityServiceEventAdapter^, CurrentHumidityGetCurrentValueRequestedEventArgs^>^ handler) 
        { 
            return _GetCurrentValueRequested += ref new Windows::Foundation::EventHandler<Platform::Object^>
            ([handler](Platform::Object^ sender, Platform::Object^ args)
            {
                handler->Invoke(safe_cast<CurrentHumidityServiceEventAdapter^>(sender), safe_cast<CurrentHumidityGetCurrentValueRequestedEventArgs^>(args));
            }, Platform::CallbackContext::Same);
        } 
        void remove(Windows::Foundation::EventRegistrationToken token) 
        { 
            _GetCurrentValueRequested -= token; 
        } 
    internal: 
        void raise(CurrentHumidityServiceEventAdapter^ sender, CurrentHumidityGetCurrentValueRequestedEventArgs^ args) 
        { 
            _GetCurrentValueRequested(sender, args);
        } 
    }

    event Windows::Foundation::TypedEventHandler<CurrentHumidityServiceEventAdapter^, CurrentHumidityGetMaxValueRequestedEventArgs^>^ GetMaxValueRequested 
    { 
        Windows::Foundation::EventRegistrationToken add(Windows::Foundation::TypedEventHandler<CurrentHumidityServiceEventAdapter^, CurrentHumidityGetMaxValueRequestedEventArgs^>^ handler) 
        { 
            return _GetMaxValueRequested += ref new Windows::Foundation::EventHandler<Platform::Object^>
            ([handler](Platform::Object^ sender, Platform::Object^ args)
            {
                handler->Invoke(safe_cast<CurrentHumidityServiceEventAdapter^>(sender), safe_cast<CurrentHumidityGetMaxValueRequestedEventArgs^>(args));
            }, Platform::CallbackContext::Same);
        } 
        void remove(Windows::Foundation::EventRegistrationToken token) 
        { 
            _GetMaxValueRequested -= token; 
        } 
    internal: 
        void raise(CurrentHumidityServiceEventAdapter^ sender, CurrentHumidityGetMaxValueRequestedEventArgs^ args) 
        { 
            _GetMaxValueRequested(sender, args);
        } 
    }

    // Property Write Events
    // ICurrentHumidityService Implementation

    virtual Windows::Foundation::IAsyncOperation<CurrentHumidityGetVersionResult^>^ GetVersionAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);
    virtual Windows::Foundation::IAsyncOperation<CurrentHumidityGetCurrentValueResult^>^ GetCurrentValueAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);
    virtual Windows::Foundation::IAsyncOperation<CurrentHumidityGetMaxValueResult^>^ GetMaxValueAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);


private:
    event Windows::Foundation::EventHandler<Platform::Object^>^ _GetVersionRequested;
    event Windows::Foundation::EventHandler<Platform::Object^>^ _GetCurrentValueRequested;
    event Windows::Foundation::EventHandler<Platform::Object^>^ _GetMaxValueRequested;
};

} } } } } 
