
//-----------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated.
//
//   For more information, see: http://go.microsoft.com/fwlink/?LinkID=623246
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

#include <windows.h>
#include <ppltasks.h>
#include <concrt.h>
#include <collection.h>
#include <windows.devices.alljoyn.interop.h>
#include <map>

#include <alljoyn_c/busattachment.h>
#include <alljoyn_c/dbusstddefines.h>
#include <alljoyn_c/AboutData.h>
#include <alljoyn_c/AboutObj.h>
#include <alljoyn_c/AboutObjectDescription.h>

#include "AllJoynHelpers.h"
#include "AllJoynBusObjectManager.h"

#define PROJECT_NAMESPACE org::alljoyn::SmartSpaces::Environment::CurrentHumidity

#include "CurrentHumidityStructures.h"
#include "TypeConversionHelpers.h"
#include "CurrentHumidityMethodResults.h"
#include "CurrentHumidityEventArgs.h"
#include "ICurrentHumidityService.h"
#include "CurrentHumiditySignals.h"
#include "CurrentHumidityProducer.h"
#include "CurrentHumidityWatcher.h"
#include "CurrentHumidityConsumer.h"
#include "CurrentHumidityServiceEventArgs.h"
#include "CurrentHumidityServiceEventAdapter.h"